server:
  port: ${app.server.port:8080}
  servlet:
    context-path: /api/v1
    encoding:
      charset: UTF-8
      force: true
  error:
    include-stacktrace: never

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 5MB


integration:
  base-url: https://www.potterapi.com/v1
  path-houses: /houses
  key: ${POTTER_KEY}

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
